### ISSUE TITLE
Does it also collect examples from properties?

### ISSUE THREAD

**Issue by sichvoge** [tsaikd/go-raml-mocker#1]
Hi, first this is a very cool project. If you like we can feature it on our "Sneak Peek" section in our forum and make a bit fuzz around that? What do you think? Are you actively planning to work on it?

QQ: Do you also collect all the examples of the object properties so that your mocking service takes that data as well? For example:

``` yaml
types:
  User:
    properties:
      firstname: 
        type: string
        example: Christian
      lastname:
        type: string
        example: Vogel
```

When I run the mocking service against a resource that defines its response as type `User` and the mime type as `application/json`, I'd like to get back:

``` json
{
  "firstname": "Christian",
  "lastname": "Vogel
}
```

Is that possible?
